spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/demo?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8080
  context-path: /qk
  error:
    path: /error
  tomcat:
    uri-encoding: UTF-8
