spring:
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/manage?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  data:
    mongodb:
      host: "172.168.177.130"
      port: 27017
      database: "test"
      username: "root"
      password: "123456"
server:
  port: 8080
  context-path: /qk
  error:
    path: /error
  tomcat:
    uri-encoding: UTF-8
